---
- hosts: all

  tasks:

    - name: clone dotfile repo
      git:
        repo: "{{ DOTFILE_REPO | default('https://github.com/mirweb/dotfiles.git') }}"
        dest: ~/.dotfiles

    - name: set authorized key
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: symlink dotfiles
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
        backup: 'yes'
        force: 'yes'
      with_items:
        - { src: ~/.dotfiles/screen/screenrc.symlink, dest: ~/.screenrc }
        - { src: ~/.dotfiles/zsh/zshrc.symlink, dest: ~/.zshrc }
        - { src: ~/.dotfiles/vim/vimrc.symlink, dest: ~/.vimrc }
        - { src: ~/.dotfiles/ssh.symlink/config, dest: ~/.ssh/config }
        - { src: ~/.dotfiles/ssh.symlink/config.d, dest: ~/.ssh/config.d }